routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'Noticias@mostrar');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('/noticias', 'Noticias');

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    //
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'titulo', 'descripcion', 'url_imagen',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Noticia;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticia::all();
        return view('home')->with(['noticias' => $noticias]);
    }
}

app/Http/Controllers/Noticias.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Noticia;

use Storage;

class Noticias extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function mostrar()
    {
        //
        $noticias = Noticia::all();
        return view('welcome')->with(['noticias' => $noticias]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
          'titulo' => 'required',
          'descripcion' => 'required'
        ]);

        $noticia = new Noticia();
        $noticia->titulo = $request->titulo;
        $noticia->descripcion = $request->descripcion;

        $img = $request->file('url_imagen');
        $ruta_imagen = time().'_'.$img->getClientOriginalName();
        Storage::disk('imagenes_blog')->put($ruta_imagen, file_get_contents($img->getRealPath()));

        $noticia->url_imagen = $ruta_imagen;

        if($noticia->save()){
            return back()->with('msj', 'Datos Guardados con Exito');
        }else{
            return back()->with('msj_error', 'Ocurrio un error al intentar guardar los datos');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $noticia = Noticia::find($id);
        return view('home')->with(['edit' => true, 'noticia' => $noticia]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
          'titulo' => 'required',
          'descripcion' => 'required'
        ]);

        $noticia = Noticia::find($id);
        $noticia->titulo = $request->titulo;
        $noticia->descripcion = $request->descripcion;

        $img = $request->file('url_imagen');
        $ruta_imagen = time().'_'.$img->getClientOriginalName();
        Storage::disk('imagenes_blog')->put($ruta_imagen, file_get_contents($img->getRealPath()));
        //eliminando imagen actual
        Storage::disk('imagenes_blog')->delete($request->ing_actual);
        $noticia->url_imagen = $ruta_imagen;

        if($noticia->save()){
            return redirect('home');;
        }else{
            return back()->with('msj_error', 'Ocurrio un error al intentar actualizar los datos');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Noticia::destroy($id);
        return redirect('home');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Panel de Control :D</div>
                <div class="panel-body">
                    @if(isset($edit))
                        @include('layouts.modificar')
                    @else
                        @include('layouts.formulario')
                    @endif
                    @include('layouts.tabla')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/formulario.blade.php
@if(session()->has('msj'))
    <div class="alert alert-success" role="alert">{{ session('msj') }}</div>
@endif
@if(session()->has('msj_error'))
    <div class="alert alert-danger" role="alert">Ocurrio un error al guardar los datos, reintente mas tarde.</div>
@endif

<form class="form-horizontal" role="form" method="POST" action="{{ url('noticias') }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="form-group">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
    <div class="form-group">
        <label for="titulo" class="col-sm-2 control-label">Título</label>
        <div class="col-sm-10">
            <input type="text" class='form-control' name="titulo" placeholder="titulo">
            @if($errors->has('titulo'))
                <span style="color:red;">{{ $errors->first('titulo') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label for="descripcion" class="col-sm-2 control-label">Descripcion</label>
        <div class="col-sm-10">
            <textarea type="text" class='form-control' name="descripcion" placeholder="descripcion"></textarea>
            @if($errors->has('descripcion'))
                <span style="color:red;">{{ $errors->first('descripcion') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label for="url_imagen" class="col-sm-2 control-label">Imágen</label>
        <div class="col-sm-10">
            <input type="file" class='form-control' name="url_imagen">
        </div>
    </div>
    <div class="form-grouup">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Crear Articulo</button>
        </div>
    </div>
</form>

resources/views/layouts/modificar.blade.php
@if(session()->has('msj'))
    <div class="alert alert-success" role="alert">{{ session('msj') }}</div>
@endif
@if(session()->has('msj_error'))
    <div class="alert alert-danger" role="alert">Ocurrio un error al guardar los datos, reintente mas tarde.</div>
@endif

<form class="form-horizontal" role="form" method="POST" action="{{ route('noticias.update',$noticia) }}" enctype="multipart/form-data">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="ing_actual" value="{{ $noticia->url_imagen }}">

    <div class="form-group">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <div class="form-group">
        <label for="titulo" class="col-sm-2 control-label">Título</label>
        <div class="col-sm-10">
            <input type="text" class='form-control' name="titulo" value="{{ $noticia->titulo }}">
            @if($errors->has('titulo'))
                <span style="color:red;">{{ $errors->first('titulo') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label for="descripcion" class="col-sm-2 control-label">Descripcion</label>
        <div class="col-sm-10">
            <textarea type="text" class='form-control' name="descripcion" > {{ $noticia->descripcion }} </textarea>
            @if($errors->has('descripcion'))
                <span style="color:red;">{{ $errors->first('descripcion') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label for="url_imagen" class="col-sm-2 control-label">Imágen</label>
        <div class="col-sm-10">
            <input type="file" class='form-control' name="url_imagen">
        </div>
    </div>
    <div class="form-grouup">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-warning">Modificar Articulo</button>
        </div>
    </div>
</form>

resources/views/layouts/tabla.blade.php
<table class="table table-hover">
    @if(isset($noticias))
        <thead>
            <th>Titulo</th>
            <th>Descripcion</th>
            <th>Imagen</th>
            <th>Acciones</th>
        </thead>
        <tbody>
            @foreach($noticias as $n)
            <tr>
                <td> {{ $n->titulo }} </td>
                <td> {{ $n->descripcion }} </td>
                <td>
                    <img src="imagenes_blog/{{$n->url_imagen}}" class ="img-responsive" alt="imagen responsiva" style="max-width:100px;"/>
                </td>
                <td>
                    <a href="noticias/{{ $n->id }}/edit" class="btn btn-warning" >Modificar</a>
                    <form action="{{ route('noticias.destroy', $n->id  ) }}" method="POST">
                        <input type="hidden" name="_method" value="DELETE">
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger" value="Eliminar">
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    @endif
</table>